-- CRGS_PRODUCTREVIEW (matches live Oracle table)

CREATE TABLE CRGS_PRODUCTREVIEW (
    EMPLOYEECODE   VARCHAR2(20)   NOT NULL,
    ROUTE          VARCHAR2(20)   NOT NULL,
    CUSTOMERCODE   VARCHAR2(20)   NOT NULL,
    CUSTOMERNAME   VARCHAR2(100)  NOT NULL,
    ITEMCODE       VARCHAR2(30)   NOT NULL,
    ITEMNAME       VARCHAR2(100)  NOT NULL,
    REASON         VARCHAR2(500),
    IMAGEPATH      VARCHAR2(255)
);

-- Existing databases: add image column if missing
-- ALTER TABLE CRGS_PRODUCTREVIEW ADD (IMAGEPATH VARCHAR2(255));
