-- Additional work reports submitted from the mobile Task screen.
-- These are NOT tasks — they record extra work done outside an assigned task.

CREATE TABLE CRGS_WORKREPORT (
    EMPLOYEECODE   VARCHAR2(20)  NOT NULL,
    ROUTE          VARCHAR2(20),
    WORKTYPE       VARCHAR2(50)  NOT NULL,
    NOTES          VARCHAR2(1000) NOT NULL,
    CUSTOMERNAME   VARCHAR2(100),
    TASKTYPE       VARCHAR2(50),
    TASKDUEDATE    DATE,
    CREATEDAT      DATE DEFAULT SYSDATE NOT NULL
);

CREATE INDEX IDX_CRGS_WORKREPORT_EMP
    ON CRGS_WORKREPORT (TRIM(EMPLOYEECODE));

CREATE INDEX IDX_CRGS_WORKREPORT_CREATED
    ON CRGS_WORKREPORT (CREATEDAT DESC);
